Repository KNUCD/backend, pull requests merged in 2022-09, with the labels that each got.

#5 Feat: BaseEntity 추가
  src/main/java/server/knucd/HackathonApplication.java
  src/main/java/server/knucd/base/BaseEntity.java
  src/main/java/server/knucd/base/BaseTimeEntity.java
Labels: enhancement

#6 Feat: GlobalExceptionHandler 추가
  src/main/java/server/knucd/exception/GlobalExceptionHandler.java
  src/main/java/server/knucd/exception/NotFoundException.java
Labels: enhancement

#7 Feat: ApiUtil 추가
  src/main/java/server/knucd/utils/api/ApiUtil.java
Labels: enhancement

#10 Feat: Complaint Entity, Repository, Service 추가
  build.gradle
  src/main/java/server/knucd/complaint/dto/CreateComplaintForm.java
  src/main/java/server/knucd/complaint/entity/Category.java
  src/main/java/server/knucd/complaint/entity/Complaint.java
  src/main/java/server/knucd/complaint/entity/Expression.java
  src/main/java/server/knucd/complaint/entity/ExpressionType.java
  src/main/java/server/knucd/complaint/entity/Location.java
  src/main/java/server/knucd/complaint/repository/ComplaintRepository.java
  src/main/java/server/knucd/complaint/service/ComplaintService.java
  src/main/java/server/knucd/member/entity/Member.java
Labels: documentation, enhancement

#11 Feat: Complaint 파일 저장 로직 및 Controller, DTO 추가
  src/main/java/server/knucd/complaint/controller/ComplaintController.java
  src/main/java/server/knucd/complaint/dto/ComplaintDTO.java
  src/main/java/server/knucd/complaint/entity/Complaint.java
  src/main/java/server/knucd/complaint/service/ComplaintService.java
  src/main/java/server/knucd/member/entity/Member.java
  src/main/java/server/knucd/member/repository/MemberRepository.java
Labels: documentation, enhancement

#15 Feat: Redis 추가
  build.gradle
  src/main/java/server/knucd/HackathonApplication.java
  src/main/java/server/knucd/config/RedisConfig.java
  src/main/java/server/knucd/utils/redis/RedisUtil.java
Labels: documentation, enhancement

#18 Feat: logging 추가
  build.gradle
  src/main/java/server/knucd/logger/LoggingFilter.java
  src/main/java/server/knucd/logger/RequestWrapper.java
  src/main/java/server/knucd/logger/ResponseWrapper.java
Labels: enhancement

#20 Feat: Expression 도메인 분리 및 Entity, Repository, Service, Controller, DTO 추가
  src/main/java/server/knucd/complaint/controller/ComplaintController.java
  src/main/java/server/knucd/complaint/dto/ComplaintDTO.java
  src/main/java/server/knucd/complaint/entity/Category.java
  src/main/java/server/knucd/complaint/entity/Complaint.java
  src/main/java/server/knucd/complaint/entity/Expression.java
  src/main/java/server/knucd/complaint/repository/ComplaintRepository.java
  src/main/java/server/knucd/complaint/service/ComplaintService.java
  src/main/java/server/knucd/expression/controller/ExpressionController.java
  src/main/java/server/knucd/expression/dto/CreateExpressionForm.java
  src/main/java/server/knucd/expression/dto/ExpressionDTO.java
  src/main/java/server/knucd/expression/entity/Expression.java
  src/main/java/server/knucd/expression/entity/ExpressionType.java
  src/main/java/server/knucd/expression/repository/ExpressionRepository.java
  src/main/java/server/knucd/expression/service/ExpressionService.java
  src/main/java/server/knucd/member/repository/MemberRepository.java
Labels: documentation, enhancement

#23 Feat: 감정표현 기능 Redis 추가
  src/main/java/server/knucd/complaint/dto/ComplaintDTO.java
  src/main/java/server/knucd/complaint/service/ComplaintService.java
  src/main/java/server/knucd/expression/controller/ExpressionController.java
  src/main/java/server/knucd/expression/entity/Expression.java
  src/main/java/server/knucd/expression/repository/ExpressionRepository.java
  src/main/java/server/knucd/expression/service/ExpressionService.java
  src/main/java/server/knucd/utils/redis/RedisUtil.java
Labels: documentation, enhancement

#24 Feat: Swagger 추가
  build.gradle
  src/main/java/server/knucd/complaint/controller/ComplaintController.java
Labels: documentation, enhancement

#27 Feat: 감정 표현 종류 수정
  src/main/java/server/knucd/expression/controller/ExpressionController.java
  src/main/java/server/knucd/expression/dto/ExpressionDTO.java
  src/main/java/server/knucd/expression/entity/ExpressionType.java
Labels: documentation, enhancement

#31 Feat: 범위로 핀 목록 검색 기능 추가
  src/main/java/server/knucd/complaint/controller/ComplaintController.java
  src/main/java/server/knucd/complaint/dto/PinDTO.java
  src/main/java/server/knucd/complaint/repository/ComplaintRepository.java
  src/main/java/server/knucd/complaint/service/ComplaintService.java
Labels: documentation, enhancement

#32 Feat: 민원 및 핀 응답 로직 수정
  src/main/java/server/knucd/complaint/controller/ComplaintController.java
  src/main/java/server/knucd/complaint/repository/ComplaintRepository.java
  src/main/java/server/knucd/complaint/service/ComplaintService.java
Labels: documentation, enhancement

#33 Feat: Member 필드 수정 및 kakaoId로 Member 찾기 추가
  src/main/java/server/knucd/member/dto/MemberDTO.java
  src/main/java/server/knucd/member/entity/Member.java
  src/main/java/server/knucd/member/entity/Role.java
  src/main/java/server/knucd/member/repository/MemberRepository.java
  src/main/java/server/knucd/member/service/MemberService.java
Labels: documentation, enhancement

#35 카카오 소셜로그인 Service 추가
  src/main/java/server/knucd/exception/CookieNotFoundException.java
  src/main/java/server/knucd/member/entity/Member.java
  src/main/java/server/knucd/member/repository/MemberRepository.java
  src/main/java/server/knucd/member/service/MemberService.java
  src/main/java/server/knucd/member/service/UserInfoDto.java
  src/main/java/server/knucd/oAuth/kakao/dto/KakaoToken.java
  src/main/java/server/knucd/oAuth/kakao/dto/KakaoTokenInfo.java
  src/main/java/server/knucd/oAuth/kakao/dto/TokenDTO.java
  src/main/java/server/knucd/oAuth/kakao/service/KakaoService.java
  src/main/java/server/knucd/utils/cookie/CookieUtil.java
Labels: documentation, enhancement

#36 Feat: Spring Security 추가
  build.gradle
  src/main/java/server/knucd/complaint/controller/ComplaintController.java
  src/main/java/server/knucd/complaint/service/ComplaintService.java
  src/main/java/server/knucd/config/SecurityConfig.java
  src/main/java/server/knucd/exception/TokenNotFoundException.java
  src/main/java/server/knucd/exception/handler/GlobalExceptionHandler.java
  src/main/java/server/knucd/exception/handler/TokenAccessDeniedHandler.java
  src/main/java/server/knucd/exception/handler/TokenNotAuthenticatedHandler.java
  src/main/java/server/knucd/expression/controller/ExpressionController.java
  src/main/java/server/knucd/expression/service/ExpressionService.java
  src/main/java/server/knucd/security/details/MemberDetails.java
  src/main/java/server/knucd/security/details/MemberDetailsService.java
  src/main/java/server/knucd/security/filter/TokenAuthenticationFilter.java
  src/main/java/server/knucd/security/filter/TokenExceptionFilter.java
  src/main/java/server/knucd/security/provider/TokenProvider.java
Labels: documentation, enhancement

#37 Feat: Security 필터링 경로 지정
  src/main/java/server/knucd/config/SecurityConfig.java
  src/main/java/server/knucd/expression/controller/ExpressionController.java
  src/main/java/server/knucd/expression/dto/ExpressionDTO.java
Labels: documentation, enhancement

#38 카카오 소셜 로그인 및 스웨거 설명 추가
  src/main/java/server/knucd/complaint/controller/ComplaintController.java
  src/main/java/server/knucd/config/SwaggerConfig.java
  src/main/java/server/knucd/expression/controller/ExpressionController.java
  src/main/java/server/knucd/logger/LoggingFilter.java
  src/main/java/server/knucd/oAuth/kakao/controller/RestKakaoController.java
  src/main/java/server/knucd/oAuth/kakao/service/KakaoService.java
  src/main/java/server/knucd/security/filter/TokenAuthenticationFilter.java
Labels: documentation, enhancement

#39 핀플레인v1.0 배포
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/server/knucd/HackathonApplication.java
  src/main/java/server/knucd/base/BaseEntity.java
  src/main/java/server/knucd/base/BaseTimeEntity.java
  src/main/java/server/knucd/complaint/controller/ComplaintController.java
  src/main/java/server/knucd/complaint/dto/ComplaintDTO.java
  src/main/java/server/knucd/complaint/dto/CreateComplaintForm.java
  src/main/java/server/knucd/complaint/dto/PinDTO.java
  src/main/java/server/knucd/complaint/entity/Category.java
  src/main/java/server/knucd/complaint/entity/Complaint.java
  src/main/java/server/knucd/complaint/entity/Location.java
  src/main/java/server/knucd/complaint/repository/ComplaintRepository.java
  src/main/java/server/knucd/complaint/service/ComplaintService.java
  src/main/java/server/knucd/config/RedisConfig.java
  src/main/java/server/knucd/config/SecurityConfig.java
  src/main/java/server/knucd/config/SwaggerConfig.java
  src/main/java/server/knucd/config/WebConfig.java
  src/main/java/server/knucd/exception/CookieNotFoundException.java
  src/main/java/server/knucd/exception/NotFoundException.java
  src/main/java/server/knucd/exception/TokenNotFoundException.java
  src/main/java/server/knucd/exception/handler/GlobalExceptionHandler.java
  src/main/java/server/knucd/exception/handler/TokenAccessDeniedHandler.java
  src/main/java/server/knucd/exception/handler/TokenNotAuthenticatedHandler.java
  src/main/java/server/knucd/expression/controller/ExpressionController.java
  src/main/java/server/knucd/expression/dto/CreateExpressionForm.java
  src/main/java/server/knucd/expression/dto/ExpressionDTO.java
  src/main/java/server/knucd/expression/entity/Expression.java
  src/main/java/server/knucd/expression/entity/ExpressionType.java
  src/main/java/server/knucd/expression/repository/ExpressionRepository.java
  src/main/java/server/knucd/expression/service/ExpressionService.java
  src/main/java/server/knucd/file/service/FileService.java
  src/main/java/server/knucd/logger/LoggingFilter.java
  src/main/java/server/knucd/logger/RequestWrapper.java
  src/main/java/server/knucd/logger/ResponseWrapper.java
  src/main/java/server/knucd/member/dto/MemberDTO.java
  src/main/java/server/knucd/member/entity/Member.java
  src/main/java/server/knucd/member/entity/Role.java
  src/main/java/server/knucd/member/repository/MemberRepository.java
  src/main/java/server/knucd/member/service/MemberService.java
  src/main/java/server/knucd/member/service/UserInfoDto.java
  src/main/java/server/knucd/oAuth/kakao/controller/RestKakaoController.java
  src/main/java/server/knucd/oAuth/kakao/dto/KakaoToken.java
  src/main/java/server/knucd/oAuth/kakao/dto/KakaoTokenInfo.java
  src/main/java/server/knucd/oAuth/kakao/dto/TokenDTO.java
  src/main/java/server/knucd/oAuth/kakao/service/KakaoService.java
  src/main/java/server/knucd/security/details/MemberDetails.java
  src/main/java/server/knucd/security/details/MemberDetailsService.java
  src/main/java/server/knucd/security/filter/TokenAuthenticationFilter.java
  src/main/java/server/knucd/security/filter/TokenExceptionFilter.java
  src/main/java/server/knucd/security/provider/TokenProvider.java
  src/main/java/server/knucd/utils/api/ApiUtil.java
  src/main/java/server/knucd/utils/cookie/CookieUtil.java
  src/main/java/server/knucd/utils/redis/RedisUtil.java
  src/test/java/server/knucd/HackathonApplicationTests.java
Labels: release
